# #+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
# #+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
# #+OPTIONS: date:t e:t email:nil f:t inline:t num:t p:nil pri:nil
# #+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
# #+OPTIONS: toc:t todo:t |:t

#+OPTIONS: toc:nil


#+TITLE: README
#+DATE: <2018-10-25 Thu>
#+AUTHOR: Stanislav Arnaudov
#+EMAIL: arnaud@localhost
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)

* FControl
** Abstract
A tool that helps you "control stuff" through the Facebook messages. Features of utility include:
- Logging of all incoming messages
- Saving a send by you to you image in some folder. You can just send some image to yourself and it will be saved on the computer where FControl is running
- Logging when your friends are using Facebook -- basically, logging when does green dots in the sidebar are present
- Logging any typing -- if someone is beginning to write a message to you and then stops and deletes is... you will now about it.


file:screenshots/cli.png
file:screenshots/log.png


*** Yes, but why though?
There was that one Facebook [[https://www.trustedreviews.com/news/facebook-messenger-unsend-delete-messages-3446074][announcement]] that they will allow messenger's users to delete sent messages as if the weren't sent at all. Now I don't like this one bit! And also I am a software developer and can talk to computers so... who cares what Facebook does, I have this app now and everything that is ever send to me will be saved. 

*** 'Muh Privacy
Yeaah, weeell, I don't know. The data is public and Facebook tracks me anyway. I am just part of the cabal by this point. At least I am tracking myself... and the people who message me.

** Installation

You can clone the repository and install all /npm/-dependencies:
#+BEGIN_SRC sh
git clone https://github.com/palikar/fcontol
cd fcontol
npm install
#+END_SRC
Or if you want to whole thing to be a little more "automatic", just install the package from [[https://www.npmjs.com/][npm]]
#+BEGIN_SRC sh
npm install fcontol
#+END_SRC

** Usage 
A simple call with ~node fcontol.js --help~ gives:
#+BEGIN_EXAMPLE
Description:
       A tool that logs different events coming from your facebook messanger (messages, typing, presence, attachments)
Usage:
       fcontrol [options]

Options:
       -e  --email        the email of your facebook acount
       -p  --pass         the password of your facebook acount
       --cli              use the tool only with command line arguments
       --restore-state    restore the state if a .appstate.json file is present
       --save-state       save the state of the app once logged in
       -h, --help         print usage information and exit
       -v, --version      show version info and exit
#+END_EXAMPLE

For first time usage, you can either just call ~node fcontrol.js --save-state~ which will prompt you for your username and password. After the first login, the application will save its state and you will no longer need to provide password and username.

\\

If you don't want to run fcontrol in non-interactive mode, you'll have to use:
#+BEGIN_SRC sh
node fcontrol.js --save-state --cli -e <email> -p <pass> 
#+END_SRC

\\

After the save is saved, fcontrol can easily be started with
#+BEGIN_SRC sh
node fcontrol.js --restore-state --cli
#+END_SRC

*** Configuration

There are two configuration files. ~lib/config.json~ and ~lib/folders.json~. ~config.json~ defines the single property ~logging_dir~ which points to a directory where the logs will be saved. ~lib/config.json~ can define several properties. I a message with the key of any property is received and the message contains an attachment, the attachment will be saved into the directory pointed by the property. For example, if I have defined the following configuration:
#+BEGIN_SRC json
{
    ":meme:" : "$HOME/memse"
}
#+END_SRC
and fcontrol is currently running, I can send and image to myself with the text "This is :meme:" and fcontrol will save the image into the directory ~memes~ inside my home directory.


*** Service
I've also written a small service file so that I can start FControl at boot time through [[https://en.wikipedia.org/wiki/Systemd][systemd]]. Look at [[file:fcontrol.service][fcontrol.service]] and [[file:install.sh][install.sh]] so that you know what you install on your system. If you are comfortable with it, just run:
#+BEGIN_SRC sh
sudo ./install.sh
#+END_SRC

Then you'll be able to use commands like:

#+BEGIN_SRC sh
sudo systemctl start fcontrol # starting fcontrol
sudo systemctl stop fcontrol # stop fcontrol
sudo systemctl enable fcontrol # start fcontrol at boot
#+END_SRC
